### ISSUE TITLE
DateTimeWidget.php hardcoded

### ISSUE THREAD

**Issue by DinoSane** [FriendsOfCake/crud-view#103]
DateTimeWidget.php itself is not "replaceable". If you create another one in the app directory it is not readed.

Regardless, the line 49 is
$val = $val->format($type === 'date' ? 'Y-m-d' : 'Y-m-d H:i:s');
meaning it is ignoring locale configurations (other dates formats)...

**Comment by ADmad** [comment]
> DateTimeWidget.php itself is not "replaceable". If you create another one in the app directory it is not readed.

We could make widgets configurable by maintaining the mapping in `defaults.php` config file and using that.

> meaning it is ignoring locale configurations (other dates formats)...

Have you set [timezoneAwareDateTimeWidget](https://github.com/FriendsOfCake/crud-view/blob/master/config/defaults.php#L24) config to true?

**Comment by DinoSane** [comment]
I was not aware of defaults.php. I'll check the options and let you know... Thanks
