### ISSUE TITLE
createViewLink and route prefixes

### ISSUE THREAD

**Issue by drmonkeyninja** [FriendsOfCake/crud-view#104]
I'm attempting to implement CrudView within an `admin` prefix; however, this results with the view link generated for index pages incorrectly pointing as the `view` action within `admin`. Should the `createViewLink` method in the `CrudViewHelper` maybe set the `prefix` to false by default like this:-

```php
public function createViewLink($title, $options = [])
    {
        return $this->Html->link(
            $title,
            ['action' => 'view', $this->getContext()->get($this->getViewVar('primaryKey')), 'prefix' => false],
            $options
        );
    }
```

Is there a simple way with the current setup of the plugin to override this for all view links as I do not want any view links remaining within my `admin` prefix?

**Comment by ADmad** [comment]
You can just extend the helper and modify to suit your needs.
