### ISSUE TITLE
Action scaffold.relations configuration ignored sometimes.

### ISSUE THREAD

**Issue by kshaaban-** [FriendsOfCake/crud-view#120]
First and foremost, thank you all very much for this amazing plugin! 👍

The issue I'm facing:

- When setting (in my controller action)

    ```php
    $this->Crud->action()->config('scaffold.relations', false);
    ```
    I still end up getting all fields for the relations in that view.
- The same issue also occurs if the `scaffold.relations_blacklist` configuration happens to include all associations currently defined for the table.

**Upon some investigating:**
[`ViewListener::_getRelatedModels()`](https://github.com/FriendsOfCake/crud-view/blob/master/src/Listener/ViewListener.php#L149-L185) returns an empty array in both aforementioned cases which is passed to [`ViewListener::_associations()`](https://github.com/FriendsOfCake/crud-view/blob/master/src/Listener/ViewListener.php#L459-L493) as `$whitelist` parameter which ultimately returns all associations assuming all associations are whitelisted.

Am I missing something of how this is supposed to work? or is it a hidden feature 😉?

**Comment by ADmad** [comment]
Closes as PR #121 is opened for this.
