### ISSUE TITLE
Unkown Method "searchManager"

### ISSUE THREAD

**Issue by TheMiller2015** [FriendsOfCake/crud-view#124]
Hello,

yesterday I started using CRUDView. I followed the tutorial/docs of CRUDView. After checkout (master and dev-master lateron) and setting up the AppController I browsed to a Controller (e.g. UsersController). Each controller now throws an Exception "Unkown Method "searchManager"".

And yes, all the Plugins (CRUD, CRUDView, BootstrapUI and Search) are loaded. I also tried Search master and dev-master lateron.

I think, this is a bug because I didn't do anything what's not in the docs.

But since CRUDView is new to me, I don't want to dig in the code and hack into it. 

So could you please check and/or give me a response, what's wrong here?

Thanks in advance.

**Comment by ADmad** [comment]
`searchManager()` method is required in table class by [search](https://github.com/friendsofcake/search) plugin, so follow it's documentation.
