### ISSUE TITLE
Adding "phinxlog" to blacklist_tables config by default

### ISSUE THREAD

**Issue by Spriz** [FriendsOfCake/crud-view#125]
I don't (and neither does @ADmad) think it makes sense to show the `phinxlog` table used by Phinx - but I'm unsure how we should implement this properly.

It could be implemented as https://gist.github.com/anonymous/c6ac8712102bef1b205f22871cd1cb08, but that's not very customisable - so what do you think should be appropriate? 

https://gist.github.com/anonymous/e090ec5cf5192e08ea7ca3b7cab46359 could easily be done for the default settings, but touching the crud action from within the ViewHelper (https://github.com/FriendsOfCake/crud-view/blob/6e7f359a62887d4aea82b2862e9d3af504184db8/src/Listener/ViewListener.php#L74) seems a bit weird.

Should it be done in https://github.com/FriendsOfCake/crud-view/blob/d8a7b03705275050b59318ea551777b69d527d04/src/Traits/CrudViewConfigTrait.php#L15? That also feels a bit weird to me.

**Comment by josegonzalez** [comment]
We can set it as the default `tables_blacklist`. If a user explicitly lists them in `tables`, we can leave it alone. If they specify `tables_blacklist`, then it overrides the defaults and they must manually specify them. I think that makes most sense here.
