### ISSUE TITLE
Irregular plurals in table names causing issues

### ISSUE THREAD

**Issue by swimboy** [FriendsOfCake/crud-view#131]
Two issues with tables with irregular plural names (like salesman -> salesmen).
1) The title of the index page will display as "Salesmens" being pluralized twice
2) Any links to salesmen from views of other tables will look for a table named "salesmens"

Fixes:
1) Commenting out lines 336-339 of src/Listener/ViewListener.php
2) removing the inflector from line 487 so that it reads just
      `$associationConfiguration[$type][$assocKey]['controller'] = $assocKey;`

**Comment by ADmad** [comment]
PR opened for fix.
