### ISSUE TITLE
How to use action_groups?

### ISSUE THREAD

**Issue by thinkingmedia** [FriendsOfCake/crud-view#132]
I can't find anything on how to use action_groups in the index field.

I think it's support to render action buttons as a drop-down button, but when I do the following it just gives me an error.

```
    public function index()
    {
        $action = $this->Crud->action();
        $action->config('scaffold', [
            'action_groups'=>[
                'index','edit','delete'
            ]
        ]);
        return $this->Crud->execute();
    }
```

Anyone know how this feature is suppose to work?

**Comment by thinkingmedia** [comment]
If I change it to the following

```
            'action_groups'=>[
                'Actions'=>['view','edit','delete'],
            ]
```

I get a button labelled "Actions" with drop-down options, but it shows View/Edit/Delete twice in the drop down. It's also adding a scroll bar to the pagination table (could be a CSS issue on my side).

**Comment by josegonzalez** [comment]
I think I've gotten this working - with documentation! - in #170, so closing.
