### ISSUE TITLE
How make an associated model optional?

### ISSUE THREAD

**Issue by thinkingmedia** [FriendsOfCake/crud-view#133]
I have a belongsTo association for a table that is optional. It can contain a null value or the ID of the association.

When I go to the add or edit view this field contains a dropdown from the association, but there is no way to select "none" for the null value.

I'm not sure how to fix this. Is this possible, and if so how?

I thinking maybe I can use the RelatedModel action events some how.

**Comment by thinkingmedia** [comment]
So, I'm not sure if this was the correct solution.

I made a copy of the `RelatedModelsListener` to my own `App` folder, and changed the `publishedRelatedModels` to this.

```
    public function publishRelatedModels($action = null)
    {
        $models = $this->models($action);

        if (empty($models)) {
            return;
        }

        $controller = $this->_controller();

        /**
         * @var \Cake\ORM\Association $association
         */
        foreach ($models as $name => $association) {
            list(, $associationName) = pluginSplit($association->name());
            $viewVar = Inflector::variable($associationName);
            if (array_key_exists($viewVar, $controller->viewVars)) {
                continue;
            }

            $finder = $this->finder($association);
            $query = $association->find()->find($finder);
            $subject = $this->_subject(compact('name', 'viewVar', 'query', 'association'));
            $event = $this->_trigger('relatedModel', $subject);

            $list = $event->subject->query->toArray();

            // mathew: Makes belongsTo that can be null an optional field.
            if ($association instanceof Association\BelongsTo) {
                $foreign_key = $association->foreignKey();
                $column = $this->_table()->schema()->column($foreign_key);
                if ($column !== null && $column['null'] === true) {
                    $list = ['' => '(none)'] + $list;
                }
            }

            $controller->set($event->subject->viewVar, $list);
        }
    }
```

This will only work if you already have a behavior in place that changes empty strings to null.

Since you need a behavior for this to work I'm guessing it doesn't qualify for a pull request.

What do you guy think?

**Comment by ADmad** [comment]
> This will only work if you already have a behavior in place that changes empty strings to null.

Empty string to null conversion will be handled by the marshaller. You don't need anything special.

**Comment by josegonzalez** [comment]
Is this still an issue?

**Comment by ADmad** [comment]
It's not. All you have to do is ensure the foreign key field is nullable and set 'empty' => true in field settings. The ORM takes care of setting the field to null if you don't select any option.
