### ISSUE TITLE
Blacklist Crud.LookupAction by default

### ISSUE THREAD

**Issue by LubosRemplik** [FriendsOfCake/crud-view#141]
When I do fresh installation of crud plugin, there is "Lookup" button
![image](https://cloud.githubusercontent.com/assets/556169/17618918/a37aec98-6082-11e6-9fd9-c74f7d266eaa.png)

But when I try to use it I am getting missing template error
![image](https://cloud.githubusercontent.com/assets/556169/17618940/c51bc516-6082-11e6-92da-63b4f06820f6.png)

imo there should be either Scaffold/lookup.ctp file or the button should not appear.

Just starting with CrudView, Crud and Search plugins so I might misunderstood.

Thanks

**Comment by ADmad** [comment]
`Lookup` action is used for ajax auto complete in search form fields and returns json response, so it doesn't need a template file.

We could perhaps hide it by default by adding it to `scaffold.actions_blacklist` config.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
