### ISSUE TITLE
Could not find listener class: CrudView.Redirect 

### ISSUE THREAD

**Issue by koffisani** [FriendsOfCake/crud-view#143]
Just installed this plugin and got this message 
> Could not find listener class: CrudView.Redirect 
> Crud\Error\Exception\MissingListenerException

How can I fix it ?

**Comment by josegonzalez** [comment]
I think you meant to set `Crud.Redirect` as a listener when setting up Crud, not `CrudView.Redirect`.

**Comment by koffisani** [comment]
@josegonzalez Thanks. Thanks very much.
