### ISSUE TITLE
Bulk actions

### ISSUE THREAD

**Issue by LubosRemplik** [FriendsOfCake/crud-view#144]
Tried to find it in documentation and in code, but can't see how the bulk actions should work out? Also not sure if it is related to crud-view or crud.

When I use following config, the bulk actions select appears

```
    public function index()
    {
        $action = $this->Crud->action();
        $action->config('scaffold.bulk_actions', [
            'delete' => 'Delete records'
        ]);
        return $this->Crud->execute();
    }
```

But when I submit, it tries to use non-existing controller. How do I need to config scaffold.bulk_actions? And do I need to handle delete it self in bulk action?

Any hint would be useful.

Thanks

**Comment by josegonzalez** [comment]
What controller does it hit? This is what I do for my bulk actions:

```
        $this->Crud->action()->config('scaffold.bulk_actions', [
            Router::url(['action' => 'deleteAll']) => __('Delete selected'),
            Router::url(['action' => 'setStatus', 'status' => 'published']) => __('Make published'),
            Router::url(['action' => 'setStatus', 'status' => 'pending-review']) => __('Set to pending'),
        ]);
```

**Comment by LubosRemplik** [comment]
@josegonzalez thanks, this example is exactly what I needed! Maybe good idea to put it into doc?

**Comment by josegonzalez** [comment]
Pull requests welcome!

**Comment by LubosRemplik** [comment]
Doc pull request already merged, closing this issue
