### ISSUE TITLE
CrudView should extend AppView

### ISSUE THREAD

**Issue by Asgraf** [FriendsOfCake/crud-view#159]
Since CrudView does not extend AppView loading custom helpers or passing custom options in AppView::initialize() does not work.

**Comment by ADmad** [comment]
Make your AppView extend CrudView.

**Comment by Asgraf** [comment]
I already tried this. AppView is never loaded.

I also tried to comment this line in AppController
````php
	public function beforeRender(Event $event) {
		/*if ($this->viewBuilder()->getClassName() === null) {
			$this->viewBuilder()->setClassName('CrudView\View\CrudView');
		}*/
	}
````
Commenting above lines causes to missing CrudViewHelper error.
I also tried to manualy load CrudViewHelper
````php
<?php
namespace App\View;

use CrudView\View\CrudView;

class AppView extends CrudView
{
	public function initialize() {
		$this->loadHelper('CrudView.CrudView');
	}
}
````

But this gave me new error:
````
Element file "Element/action-header.ctp" is missing.
Cake\View\Exception\MissingElementException
````
So there is no easy way to do this without getting tons of errors

**Comment by ADmad** [comment]
You need to call `parent::initialize();` in `AppView::initialize()`, that's PHP OOP 101.
