### ISSUE TITLE
Index grid improvements

### ISSUE THREAD

**Issue by DinoSane** [FriendsOfCake/crud-view#165]
Hi,
I faced the need to improve the index action result due customers requirements, and would be amazing if some of them came with the core:

- Use of jQuery Bootgrid as main grid as it bring outstand features (http://www.jquery-bootgrid.com/examples)
  - Search input field
  - Select fields to show
  - Select number of rows to show
  - A refresh button 
  - I also include 3 buttons to print the grid filtered records as PDF, XLS and HTML 

An example : (http://admin.motum.com.br/screen.png)

Let me know if I can help in any way!

**Comment by josegonzalez** [comment]
I've opened up specific issues for everything so we can start working on them one by one :)

**Comment by DinoSane** [comment]
Maybe you would consider a new one already! :-)

The "Copy" Action. 

One press the copy action button (index page) row of register "{id:2,name:'paul',age:'10'}" and the add form is shown with those values already filled.

**Comment by josegonzalez** [comment]
Sounds like a new action that would need to be set in Crud and then have CrudView integration. Can you open an issue in Crud for that?

**Comment by DinoSane** [comment]
Done [#537](https://github.com/FriendsOfCake/crud/issues/537)
