### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by josegonzalez** [FriendsOfCake/crud-view#190]
Not sure how we can write tests for this. We can do one of two things (or both)

- Integration Tests: Perhaps we create actions, call render, and verify that the produced HTML is the same as some files on disk?
- Unit Tests: Verify that the listener logic does what it says it should do, based on the provided action config? Same for other classes.

We should probably aim for about 80-90% coverage regardless. All functionality *should* be tested.

Also a good opportunity for removing as much logic as possible from the templates and moving them either into listeners/traits or helpers.

Thoughts?

**Comment by ADmad** [comment]
We will probably need both unit and integration tests.

**Comment by josegonzalez** [comment]
Tests are being written!
