### ISSUE TITLE
Select element not getting populated with uuid foreign key on add

### ISSUE THREAD

**Issue by bdodds** [FriendsOfCake/crud-view#204]
Hi folks.  I wrote up the following code:

https://gist.github.com/bdodds/148dcd7eef6c724627f4d0596f09d004

and if I go to /clientpocs/add the select dropdown for client_id is populated with sequential integers starting at 0, rather than the uuids that are in the 'id' column of the client table.  I created these databases through a migrate, and if I go to /clientpocs/edit and look at the variables, I see a clientpoc->client->id variable with the right information, in fact you can see I had to pull clientpoc->client->name out to display in the list.  Hopefully I'm doing something wrong, but @hmic intimated this may be a bug.  So, thanks, and let me know what other information you might need.

**Comment by bdodds** [comment]
Versions for reference: 
cakephp/cakephp                       3.5.0   The CakePHP framework
friendsofcake/crud                    5.1.3   CakePHP Application development on steroids - rapid prototyping / scaffolding & productio...
friendsofcake/crud-view               0.9.1   View layer for CRUD

**Comment by ceeram** [comment]
bindingKey and foreignKey of hasOne Clients seems to be mixed. looking at the field names, looks you would want to use belongsTo Clients instead of hasOne in your ClientpocsTable (and vice versa also on Client it needs to be changed the other way around)

**Comment by ADmad** [comment]
Rule to thumb:  The table containing foreignkey always "belongsTo" the other.

**Comment by bdodds** [comment]
sonofagun.  Sorry for the noob mistake, thanks for the help.  It was both the belongsTo/hasOne and the bindingKey/foreignKey that were swapped.  I guess my brain works the wrong way.
