### ISSUE TITLE
How to customize css of crud-view

### ISSUE THREAD

**Issue by sunil-makwana008** [FriendsOfCake/crud-view#205]
#i want to use my material-design css but crud-view overwrite css
and how to customize crud-view 
give file name where i can change

**Comment by ADmad** [comment]
Crud view doesn't overwrite any css. It has `friendsofcake/ bootstrap-ui` as dependency and uses bootstrap classes in the generated HTML. So you can use bootstrap's css and any additional bootstrap theme css.
