### ISSUE TITLE
DateTimeWidget shoud not ignore custom html attributes

### ISSUE THREAD

**Issue by asgraf** [FriendsOfCake/crud-view#211]
### What you did
````php
echo $this->Form->control('text_test',['type'=>'text','data-custom'=>'xyz']);
echo $this->Form->control('datetime_test',['type'=>'datetime','data-custom'=>'xyz']);
````
### What happened
````html
...
<input name="text_test" class="form-control" data-custom="xyz" id="text-test" type="text">
...
<input class="form-control" name="datetime_test" value="2017-09-27 03:04:21" id="datetime-test" role="datetime-picker" data-locale="pl_PL" data-format="" type="text">
...
````
### What you expected to happen
````html
...
<input name="text_test" class="form-control" data-custom="xyz" id="text-test" type="text">
...
<input data-custom="xyz" class="form-control" name="datetime_test" value="2017-09-27 03:04:21" id="datetime-test" role="datetime-picker" data-locale="pl_PL" data-format="" type="text">
...
````

**Comment by ADmad** [comment]
Probably to fix the issue is welcome.

**Comment by josegonzalez** [comment]
@Asgraf do you have a complete example? The above seems like its less related to crud-view and more bootstrap-ui, given that my usage here is via controllers, not via ctp files.

**Comment by Asgraf** [comment]
@josegonzalez I already work on another project now.
If i recall correctly i had project with tables with two datetime collumn fields.
Lets call them for example start_on and end_on.
I wanted to add custom attributes to inputs so they could point to each other.
My goal was to interconnect those wigets via my custom script to create datetime-range picker.
(end_on datetime value should always be greater/later than start_on value)

**Comment by josegonzalez** [comment]
Gotcha, makes sense. Let me see if I can reproduce this.

**Comment by ADmad** [comment]
This is no longer an issue as the Cake 4 uses HTML5 datetime inputs by default.
