### ISSUE TITLE
Action button code duplication

### ISSUE THREAD

**Issue by Asgraf** [FriendsOfCake/crud-view#212]
This IF is unnecessary and can be removed
https://github.com/FriendsOfCake/crud-view/blob/2a59b15483154f185c738bef20483f477c14c3cb/src/Template/Element/actions.ctp#L85-L92

Its already handled here
https://github.com/FriendsOfCake/crud-view/blob/2a59b15483154f185c738bef20483f477c14c3cb/src/Template/Element/action-button.ctp#L7-L10

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
