### ISSUE TITLE
Cannot change action button class

### ISSUE THREAD

**Issue by Asgraf** [FriendsOfCake/crud-view#213]
https://github.com/FriendsOfCake/crud-view/blob/2a59b15483154f185c738bef20483f477c14c3cb/src/Template/Element/actions.ctp#L84
This line always overrides button class.
This prevents from setting custom button class in scaffold.extra_actions

**Comment by ADmad** [comment]
PR to fix the issue is welcome.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
