### ISSUE TITLE
DateTimeWidget HTML5 compatible

### ISSUE THREAD

**Issue by asgraf** [FriendsOfCake/crud-view#214]
For better mobile experience (native datepicker) DateTimeWidget probably should output html5 ````<input type="datetime-local">```` instead of ````<input type="text">````

**Comment by ADmad** [comment]
Native datetime input support is still not consistent across desktop browsers. I doubt the js datetime picker will work properly if we change the input type. The primary use case for this plug in is admin areas which would generally be accessed on desktop not mobile. 

So I don't want to compromise desktop usage for getting native date picker on mobile.

**Comment by Asgraf** [comment]
I use Modernizr to get it consistent on my site.
````js
	if(!Modernizr.inputtypes['datetime-local']) {
		$('input[type=datetime-local]').datetimepicker();
	}
	if(!Modernizr.inputtypes.date) {
		$('input[type=date]').datepicker();
	}
	if(!Modernizr.inputtypes.time) {
		$('input[type=time]').timepicker();
	}
````
This way javascript widgets are only applied when native browser support is not present.

**Comment by ADmad** [comment]
Cake 4 uses HTML5 datetime inputs by default so this is no longer an issue.
