### ISSUE TITLE
Notice (8): Undefined variable: disableSidebar

### ISSUE THREAD

**Issue by rkaartikeyan** [FriendsOfCake/crud-view#230]
I am beginner to Crud View, i followed all the steps that mentioned in the document page(https://crud-view.readthedocs.io/en/latest/).

But when i Open URL in browser i got many errors(please have a look the attached screenshot).

Please help me to resolve this issue.

Thanks in advance.

![image](https://user-images.githubusercontent.com/3778591/35507390-95614f7c-0512-11e8-8396-47997418d250.png)

**Comment by josegonzalez** [comment]
@rkaartikeyan this looks like there might be a different error on that page - potentially you're not loading the CrudView in your project?

Regardless, I'm going to make a small bugfix so we properly check for the existence of that variable.

**Comment by josegonzalez** [comment]
Closing as there is now a pull request open. Feel free to join the cakephp slack if you're having further trouble configuring this plugin.
