### ISSUE TITLE
Is it possible to integrate crud-view with an admin theme?

### ISSUE THREAD

**Issue by MarcHe124** [FriendsOfCake/crud-view#256]
I found the Gentelella theme is beautiful but it does not automatically generate CRUD actions and pages for db tables like crud-view. Is it possible that we can integrate an admin theme like Gentelella with crud-view?

https://github.com/backstageel/cakephp-gentelella-theme

**Comment by ADmad** [comment]
CrudView uses the https://github.com/FriendsOfCake/bootstrap-ui plugin, so it's templates have bootstrap compatible markup. So theoretically you can use any bootstrap theme out there, just need to include the extra css and js files. Also you can also override any crud view template the same way you can override a plugin template in Cake.
