### ISSUE TITLE
Create action links with composite primary key

### ISSUE THREAD

**Issue by change2lives** [FriendsOfCake/crud-view#257]
We are working with an existing database that has tables with composite primary keys and the crud-view plug is not able to create the action links. Are we missing something? It works great when the table's primary key is one field. One table is defined as follows:

$this->setTable('brdrpt_d_test');
$this->setDisplayField('DOC_KEY');
 $this->setPrimaryKey(['DOC_KEY','ASSIGN_TO']);

The error we are getting is
"Notice (8): Array to string conversion [ROOT\vendor\friendsofcake\crud-view\src\Template\Element\actions.ctp, line 56]"

If we disable the crud-view plug in and only use cakephp we can use the composite key. We would like to find a solution. Thanks in advance.

**Comment by ADmad** [comment]
Closing as there are currently no plans to support composite primary keys.
