### ISSUE TITLE
Use flatpicker datetime picker for new major version of plugin supporting Cake 4.

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/crud-view#261]
Currently the plugin uses https://github.com/Eonasdan/bootstrap-datetimepicker for datetime fields, which is no longer actively developed.

Upon googling it's successor seems to be https://github.com/tempusdominus/bootstrap-4 but that too hasn't seen any development activity or issues triaging in a long time.

Hence my proposal to switch to https://github.com/flatpickr/flatpickr for next major version of the plugin.

- One nice feature this widget has is it can be configured to use 2 different format for [display to user](https://flatpickr.js.org/examples/#human-friendly-dates) and for value submitted to server. This can be quite handy for those who need to localize the display format but still want a common format for POSTed value.

- The [formatting token](https://flatpickr.js.org/formatting/) it uses are also very similar to PHP `strtotime()` tokens so we won't need a large token conversion hash that we currently have in `DateTimeWidget`.

P.S. Cake 4 uses HTML date / datetime inputs by default instead of selects so we'll provide option to turn off use of JS datetime picker.

**Comment by jippi** [comment]
seems good to me :)
