### ISSUE TITLE
Can't add or insert via crud-view due to invalid datetime format on `created` field.

### ISSUE THREAD

**Issue by geoidesic** [FriendsOfCake/crud-view#269]
Here's my table migration:
```
$this->table('cocktails')
			->addColumn('name', 'string', [
				'default' => null,
				'limit' => 255,
				'null' => false,
			])
			->addColumn('description', 'string', [
				'default' => null,
				'limit' => 255,
				'null' => false,
			])
			->addColumn('created', 'datetime', [
				'default' => 'CURRENT_TIMESTAMP',
				'limit' => null,
				'null' => false,
			])
			->addColumn('modified', 'datetime', [
				'default' => null,
				'limit' => null,
				'null' => true,
			])
			->create();
```
I have crud and crud-view installed and the admin interface is browsable. When I try to add or edit a cocktail however I get the following error:
```
Error: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '10/24/2019 12:00 AM' for column 'created' at row 1
```
For the `edit` I was changing the `name` field (so not changing the `created` value at all).
For the `add` context I used the supplied datepicker.

P.S. the Model does have the `Timestamp` behaviour attached to it.

**Comment by ADmad** [comment]
CakePHP doesn't support default set to `CURRENT_TIMESTAMP`. Just set it to null and let the TimestampBehavior set required values.

**Comment by geoidesic** [comment]
Thanks. I've altered the schema as suggested now but I'm still getting the same error.

**Comment by ADmad** [comment]
The database doesn't accept values in the format shown in error message. So either use the `format` option for the field to set format for the datetime picker to format acceptable to the db or turn on locale based string parsing using the `DateTimeType` db class.

Consultant the CakePHP or use one of the help forums for support. There's no bug here which needs to be addressed.

**Comment by geoidesic** [comment]
Then maybe the docs should be updated with this information? 

Currently the installation instructions are incomplete. This is all intended to work with the ORM (otherwise what's the point of crud) but there's no mention of any of the requirements you mention above wrt massaging your models into the required shape for `crud-view`.

Currently the installation instructions require one to make certain assumptions about the starting point from which one can follow the instructions... my assumptions are that one could start as follows:
1. Create a completely new project
2. Run the migration for the table
3. Bake the model

Using this starting point, if you follow the crud-view installation and setup instructions, then you will get the error I reported on add and insert. Whereas with the standard admin interface via bake you will not get this error.

So imho either the docs need updating to explain all the extra requirements you mentioned above or this is a bug. Otherwise it simply doesn't do what it says on the tin.

Ideally imho, this should work out the box, so one shouldn't be required to have to alter every model (which is what you seem to be suggesting above) in order to get it to work with a plugin which is supposed to integrate seamlessly.

**Comment by ADmad** [comment]
You are welcome to submit updates for the docs. We rely on community contributions for improvements.
