### ISSUE TITLE
Composer error when install crud-view in cakephp 4.1.x

### ISSUE THREAD

**Issue by vnt** [FriendsOfCake/crud-view#278]
Hi,
How do I install crud-view in cakephp 4.1.x?

Using composer:

composer require friendsofcake/crud-view

I get this error:

Using version ^0.14.0 for friendsofcake/crud-view
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for friendsofcake/crud-view ^0.14.0 -> satisfiable by friendsofcake/crud-view[0.14.0].
    - friendsofcake/crud-view 0.14.0 requires cakephp/cakephp ^3.7 -> satisfiable by cakephp/cakephp[3.7.0, 3.7.0-RC1, 3.7.0-RC2, 3.7.0-RC3, 3.7.0-beta1, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5, 3.7.6, 3.7.7, 3.7.8, 3.7.9, 3.8.0, 3.8.0-RC1, 3.8.0-RC2, 3.8.0-RC3, 3.8.0-beta1, 3.8.1, 3.8.10, 3.8.11, 3.8.12, 3.8.13, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.8.7, 3.8.8, 3.8.9, 3.9.0, 3.9.0-RC1, 3.9.0-RC2, 3.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by ADmad** [comment]
`composer require friendsofcake/crud-view:0.40@beta`.

**Comment by vnt** [comment]
composer require friendsofcake/crud-view:"0.40@beta"

[InvalidArgumentException]                                                   
  Could not find package friendsofcake/crud-view in a version matching 0.40@beta

**Comment by ADmad** [comment]
You can add `"minimum-stability": "beta"` to your app's composer.json and use the exact version for now `0.40.0-beta2`.

**Comment by vnt** [comment]
thanks a lot
