### ISSUE TITLE
There are many errors 500 in version 0.40.0

### ISSUE THREAD

**Issue by vnt** [FriendsOfCake/crud-view#283]
Hi,
I have installed the new version 0.40.0 and i received the following errors:

`GEThttp://cake4/crud_view/css/local.css
GEThttp://cake4/css/4.css
[HTTP/1.1 500 Internal Server Error 30060ms]
GEThttp://cake4/js/3.js
[HTTP/1.1 500 Internal Server Error 30060ms]
GEThttp://cake4/crud_view/js/local.js
[HTTP/1.1 500 Internal Server Error 30059ms]

Uncaught ReferenceError: jQuery is not defined
    jQuery 2
jquery.dirtyforms.min.js:16:25
    jQuery 2
GEThttp://cake4/crud_view/js/local.js
[HTTP/1.1 500 Internal Server Error 30051ms]

GEThttp://cake4/debug_kit/js/toolbar.js?1599096306
[HTTP/1.1 500 Internal Server Error 30058ms]
`

**Comment by ADmad** [comment]
@vnt Can you try using the `master` branch and confirm that the issue is resolved before I make a release? (I mistakenly pushed the fixed to master instead of a bugfix branch).

**Comment by vnt** [comment]
Some errors are fixed.
These errors are still there:

GEThttp://cake4/crud_view/css/local.css[HTTP/1.1 500 Internal Server Error 30079ms]
GEThttp://cake4/crud_view/css/local.css Stato500 Internal Server Error
GEThttp://cake4/crud_view/js/local.js [HTTP/1.1 500 Internal Server Error 30078ms]
GEThttp://cake4/crud_view/js/local.js[HTTP/1.1 500 Internal Server Error 30004ms]

**Comment by ADmad** [comment]
Can you provided me some details, what's the error info shown when you access those URLs directly (or in logs)?

**Comment by vnt** [comment]
URLs directly

GEThttp://cake4/crud_view/css/local.css
[HTTP/1.1 500 Internal Server Error 30233ms]

	
GET
	http://cake4/crud_view/css/local.css
Stato500
Internal Server Error
VersioneHTTP/1.1
Trasferito711 B (dim. 535 B)

    	
    Connection
    	close
    Content-Length
    	535
    Content-Type
    	text/html; charset=iso-8859-1
    Date
    	Mon, 28 Sep 2020 08:39:51 GMT
    Server
    	Apache
    	
    Accept
    	text/css,*/*;q=0.1
    Accept-Encoding
    	gzip, deflate
    Accept-Language
    	it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
    Cache-Control
    	no-cache
    Connection
    	keep-alive
    Cookie
    	csrfToken=2793aabaa509b885adf96362ad346e9b44465cf477f6ca7d9555372a; PHPSESSID=98pjtls1chogh4j7f3jm64i17p
    Host
    	cake4
    Pragma
    	no-cache
    Referer
    	http://cake4/categories/view/5
    User-Agent
    	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:81.0) Gecko/20100101 Firefox/81.0

view-source:http://cake4/crud_view/css/local.css
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, you@example.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

**Comment by ADmad** [comment]
This looks like an error page generated by your webserver and not CakePHP, which means the request is not even reaching the cake app.

What's the URL to your app root/homepage?
