### ISSUE TITLE
Cake4 - Assets do not properly load

### ISSUE THREAD

**Issue by nvande** [FriendsOfCake/crud-view#284]
With Cake4, the assets listed in `asset_compress.ini` aren't being properly loaded, resulting in the view being un-styled.

Removing option values by changing the scanner mode from default to raw on line 8 of `defaults.php` results in the view being styled again.

**Comment by ADmad** [comment]
I don't have any issues with CSS loading with the demo app https://github.com/FriendsOfCake/crud-demo-app/tree/cake-4

So you'll have to provide details about exactly what error you are getting.

**Comment by ADmad** [comment]
The demo has some layout issue but that's because the HTML is not properly update for Bootstrap 4, assets load just fine.

**Comment by nvande** [comment]
I am getting `uncaught reference error: jQuery is not defined` as well as 404s for each of the unloaded stylesheets, which seem to come in as 'localhost\css\4.css' etc

I can check out the demo to see what might be done differently there.

Thanks!

**Comment by ADmad** [comment]
This sounds like duplicate of #283. Are you using the latest 0.40.1 release?

**Comment by ADmad** [comment]
No, it was merged into master. So use that or better yet the 0.40 releases.
