### ISSUE TITLE
Is it prepared for Bootstrap 4?

### ISSUE THREAD

**Issue by matscav** [FriendsOfCake/crud-view#291]
Hello everyone,

I tried the plugin for a quick backend I need to make, but some things seem broken (left navbar, action buttons on edit).
It looks like the views were developed for Bootstrap 3, but BootstrapUI plugin comes with Bootstrap 4.
Are there any plans to fix that?

Thank you!

**Comment by ADmad** [comment]
Yes the HTML in templates needs updating as per Boostrap 4. Any help is appreciated.
