### ISSUE TITLE
"Improve this doc" link broken on crud-view.readthedocs.org

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/crud-view#46]

**Comment by ADmad** [comment]
Links are broken because the `branch` variable seems to be missing in the template.

**Comment by josegonzalez** [comment]
Fixed by the following commits:

- 87282183f5988760af9a6b44e3f1fa1a94839ad6
- c74272ea3de57bb2e27ff49306a293e0dd7c505e
