### ISSUE TITLE
DateTimeWidget time zone issue

### ISSUE THREAD

**Issue by GuidoHendriks** [FriendsOfCake/crud-view#87]
To display input fields for `datetime` properties CrudView use the `DateTimeWidget`. This widget uses a date picker which detects the clients time zone. This causes an unexpected behavior when the clients time zone doesn't match the one configured in the app config.

For my app I use UTC, but my computer is at UTC+2.

For example, this are the the values I'm seeing at the moment:

**`value`:**
2015-09-30 16:53:41

**`data-timestamp`:**
1443632021
This is the timestamp for `value` on UTC.

**Displayed value after loading date picker:**
30/09/2015 18:53
This is my current time on UTC+2.

Now when I post it gets interesting. Since it's posting the current time in UTC+2, it goes wrong:

**`value`:**
2015-09-30 18:53:00
This was the time in UTC+2, but the app now assumes it's UTC.

**`data-timestamp`:**
1443639180
This is the timestamp for `value` on UTC.

**Displayed value after loading date picker:**
30/09/2015 20:53
Now the time is 2 hours later than I selected.

I don't think the date picker should look at the clients time zone by default, or if it does it should send it along so it can be saved correctly. Been looking into the configuration options of https://github.com/Eonasdan/bootstrap-datetimepicker/, but with the used version there doesn't seem to be a way to get it right.

**Comment by lorenzo** [comment]
You will need to change the input value before saving. I do this using a custom database type

**Comment by GuidoHendriks** [comment]
It's not about saving, I got that covered. If I either switch my own time zone to UTC or the apps timezone to UTC+2 it's fixed.

**Comment by lorenzo** [comment]
It is definitely about saving. That is how I solved my issue

**Comment by GuidoHendriks** [comment]
Saving the datetime works just fine, the problem is client-side.

When I add an entity with "01-10-2015 14:40", it gets saved correctly - I triple checked this in database. When I edit it, the values of the `value` and `data-timestamp` properties of the `input` field are correct, but the displayed time is 2 hours later because of the client-side formatting, which converts it to my timezone using Moment.js.

There are workarounds (http://jsfiddle.net/TC6Gr/37/ i.e.) around to translate it back to UTC before posting. But that's not the kinda solution I want to ship.

**Comment by GuidoHendriks** [comment]
Bumping the version of the datepicker would probably solve my problem, since they added a way to set the time zone in latest release:

https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1242

**Comment by ADmad** [comment]
@GuidoHendriks Make a PR updating the lib version [here](https://github.com/FriendsOfCake/crud-view/blob/master/config/defaults.php)

**Comment by josegonzalez** [comment]
@lorenzo do you have an example custom type for DateTime? The picker does weird stuff for US locale and can't be saved as is.: https://cl.ly/1c1d1e400p1J

**Comment by lorenzo** [comment]
what's the weird stuff for that locale?

**Comment by josegonzalez** [comment]
That gets saved to the database in that exact format, and the database expects something like `2016-12-06 09:35:00`.

**Comment by lorenzo** [comment]
@josegonzalez here's a short version of it https://gist.github.com/lorenzo/41b568a1b0840ffd0485 I know @davidyell has an up to date version.

Keep in mind that the idea of the locale aware widget started when cake had `useLocaleParser()` on by default in bootstrap.php. That is not the case anymore since it caused a lot of confusion.

**Comment by josegonzalez** [comment]
So is the crud-view default wrong now?
