### ISSUE TITLE
DateTimeWidget doesn't work well with en_GB locale

### ISSUE THREAD

**Issue by GuidoHendriks** [FriendsOfCake/crud-view#88]
I've been trying to use the `DateTimeWidget` in my app, which uses the `en_GB` locale. Because of the line below, only "en" gets passed to the date picker which causes the problem (defaults to US, I guess). 
https://github.com/FriendsOfCake/crud-view/blob/master/src/View/Widget/DateTimeWidget.php#L29

When I post the current time -  "09/30/2015 7:07 PM" - it's parsed to "06/09/2017 9:07 AM" because of the wrong locale.

I tried removing the `locale_get_primary_language()` which seems to fix it. Does anyone know why it's been used and if it has to stay here?

Happy to PR if needed, but thought I'd ask you guys before.

**Comment by lorenzo** [comment]
Not sure if it is needed, can you maybe try with different locales?

**Comment by GuidoHendriks** [comment]
Tried using `nl_NL` (Dutch for the Netherlands) and `nl_BE` (Dutch for Belgium) they both work correctly, but only `nl` seems to be defined. The used library, Moment.js, automatically falls back to the deepest known locale, as tested in the following file:
https://github.com/moment/moment/blob/25cc720fbaab7323a1016cd0beb6a36e349c41be/src/test/moment/locale.js#L73-L77

**Comment by lorenzo** [comment]
Ok, then i think it is safe to remove
